//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit8Assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bit8Entities : DbContext
    {
        public Bit8Entities()
            : base("name=Bit8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<StudentSemester> StudentSemesters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<SemesterDiscipline> SemesterDisciplines { get; set; }
    }
}
