//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit8Assignment
{
    using Bit8Assignment.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public partial class Semester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semester()
        {
            this.StudentSemesters = new HashSet<StudentSemester>();
            this.SemesterDisciplines = new HashSet<SemesterDiscipline>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSemester> StudentSemesters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemesterDiscipline> SemesterDisciplines { get; set; }

        public SelectList DisciplinesSelectList = new SelectList(new Bit8Entities().Disciplines, "ID", "DisciplineName");
        public int DisciplineID { get; set; }

        public List<SemesterDiscipline> SemesterDisciplineList => new Bit8Entities().SemesterDisciplines.Where(x => x.SemesterID == Id).ToList();

    }
}
