//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit8Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSemester
    {
        public int Id { get; set; }
        public int SemesterID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
