CREATE TABLE [dbo].[StudentSemester]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(ID),
	SemesterID INT NOT NULL FOREIGN KEY REFERENCES Semesters(ID)
)
